// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzygkkkoifgmnabtwfsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6eWdra2tvaWZnbW5hYnR3ZnNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NjAzNzQsImV4cCI6MjA2NDAzNjM3NH0.hZqkYm861b6NmngrgTnFO4YKhnJHUFHHcB1N8xSWWaY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);